### ISSUE TITLE
How about zip-wrapper?

### ISSUE THREAD

**Issue by pronebird** [chaddjohnson/unzip-wrapper#1]
How about a companion library – zip-wrapper? :+1:

**Comment by chaddjohnson** [comment]
That's not a bad idea, though I have no time for this now.

The main motive for writing this library was the need to repair archives prior to extraction.

Is there anything in particular you see a zip-wrapper module offering?

**Comment by pronebird** [comment]
I wrote my own zip-wrapper today: https://github.com/pronebird/zip-wrapper. I needed something simple to zip a single folder.

**Comment by pronebird** [comment]
I pushed my own implementation on npm :-) Now I have a nice couple of unzip and zip wrappers!
